controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_cart:
  path: /cart
  controller: App\Controller\CartController::index
add_cart:
  path: /add/{id}
  controller: App\Controller\CartController::add
app_produit_show:
  path: /product/show/{id}
  controller: App\Controller\ProductController::show

app_produits:
  path: /products
  controller: App\Controller\ProductController::index

app_produit_ajouter:
  path: /product/add
  controller: App\Controller\ProductController::ajouter

app_product_mouse:
  path: /products/mouses
  controller: App\Controller\ProductController::showMouses

app_product_keyboard:
  path: /products/keyboards
  controller: App\Controller\ProductController::showKeyboards

app_product_headset:
  path: /products/headsets
  controller: App\Controller\ProductController::showHeadsets

app_product_mousepad:
  path: /products/mousepads
  controller: App\Controller\ProductController::showMousepads

app_product_screen:
  path: /products/screens
  controller: App\Controller\ProductController::showScreens
