controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_cart:
  path: /cart
  controller: App\Controller\CartController::index
add_cart:
  path: /add/{id}
  controller: App\Controller\CartController::add
app_produit_show:
  path: /product/show/{id}
  controller: App\Controller\ProductController::show

app_produits:
  path: /products
  controller: App\Controller\ProductController::index

app_produit_ajouter:
  path: /product/add
  controller: App\Controller\ProductController::ajouter
